version: "1.0.0"
description: Classification model hyperparameters

vectorizer:
  ngram_range: [1, 3]  # Unigrams, bigrams, trigrams
  max_features: 50000
  min_df: 2  # Ignore terms in <2 documents
  max_df: 0.95  # Ignore terms in >95% of documents

feature_selection:
  enabled: true
  method: chi2
  k: 20000  # Top 20k features

classifier:
  max_iter: 500
  solver: lbfgs
  n_jobs: -1  # Use all CPU cores
  class_weight: balanced  # Handle imbalanced classes

calibration:
  enabled: true
  method: sigmoid
  cv: 3  # 3-fold cross-validation
  min_samples_per_class: 3

scoring:
  bands:
    high:
      min: 70
      max: 100
      label: High
    medium:
      min: 40
      max: 69
      label: Medium
    low:
      min: 0
      max: 39
      label: Low
  max_supporting: 3  # Number of supporting CET areas to return

stop_words:
  # Generic SBIR terms
  - phase
  - sbir
  - sttr
  - award
  - contract
  - proposal
  - program
  - project
  - research
  - development
  - technology
  - technical
  # Business terms
  - company
  - firm
  - small
  - business
  - innovative
  - innovation
  # Proposal boilerplate
  - objective
  - approach
  - anticipated
  - benefits
  - commercial
  - applications
  - potential
  - proposed
  - develop
  - provide
